name: build

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Lint and test
      #   run: |
      #     black --check .
      #     ruff .
      #     pytest

  firmware:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firmware
    steps:
      - uses: actions/checkout@v4

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: pio-${{ runner.os }}-${{ hashFiles('platformio.ini') }}
          restore-keys: |
            pio-${{ runner.os }}-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Generate secret
        run: cp include/secret_template.h include/secret.h

      - name: Build firmware
        run: pio run
